Upgade kbfsd to v1.0.0
The daemon was rewritten and now we are able to start and stop it
reliably.

diff --git a/security/kbfsd/files/kbfsd.in b/security/kbfsd/files/kbfsd.in
--- a/security/kbfsd/files/kbfsd.in
+++ b/security/kbfsd/files/kbfsd.in
@@ -31,40 +31,41 @@
 . /etc/rc.subr
 
 name='kbfsd'
-rcvar="${name}_enable"
+rcvar='kbfsd_enable'
 
-load_rc_config "${name}"
+load_rc_config 'kbfsd'
 
 # Default settings.
 : "${kbfsd_enable:=no}"
-: "${kbfsd_username:?'kbfsd_username cannot be empty.'}"
 : "${kbfsd_mountpoint:=/keybase}"
-: "${kbfsd_keybase_username:="${kbfsd_username}"}"
+: "${kbfsd_user:?'kbfsd_user cannot be empty.'}"
+# It has to be done manually because the su(1) mechanism present in rc.subr(8)
+# uses the "-m" flag, which causes kbfsfuse to look for files in root's
+# directories instead of the directories of ${kbfsd_user}.
+: "${kbfsd_env:="HOME=/home/${kbfsd_user}"}"
+: "${kbfsd_keybase_username:="${kbfsd_user}"}"
 
-command="%%LOCALBASE%%/bin/kbfsfuse"
-command_args="-log-to-file ${kbfsd_mountpoint}"
+# This location is a popular one for other Keybase-related files.
+pidfile="/home/${kbfsd_user}/.config/keybase/kbfsd.${kbfsd_user}.pid"
 
-start_precmd='kbfsd_prestart'
-start_cmd='kbfsd_start'
-# stop_cmd is not needed since procname and pidfile are set.
+# The "procname" variable has to be set because we use daemon(8) here and the
+# process name does not match the "command" variable.
+procname='%%LOCALBASE%%/bin/kbfsfuse'
+command='/usr/sbin/daemon'
+command_args="-p ${pidfile} %%LOCALBASE%%/bin/kbfsfuse -log-to-file ${kbfsd_mountpoint}"
 
-# This location is used by many other Keybase-related PID files.
-pidfile="/home/${kbfsd_username}/.config/keybase/kbfsd.${kbfsd_username}.pid"
-# The process name is equal to "daemon" because kbfsfuse is started by
-# daemon(8).
-procname="daemon"
+start_precmd="kbfsd_prestart"
+stop_postcmd="kbfsd_poststop"
 
-required_dirs="${kbfsd_mountpoint}"
-required_files="/home/${kbfsd_username}/.config/keybase/kbfsd.sock /home/${kbfsd_username}/.config/keybase/keybased.sock"
 required_modules='fuse'
 
 kbfsd_prestart()
 {
-	local _m
+	local _f
 
 	# Make sure that the username is valid.
-	if ! id -u -- "${kbfsd_username}" > /dev/null 2>&1; then
-		err 1 "kbfsd_username is set to '${kbfsd_username}' which is not a valid user."
+	if ! id -u -- "${kbfsd_user}" > /dev/null 2>&1; then
+		err 1 "kbfsd_user is set to '${kbfsd_user}' which is not a valid user."
 	fi
 
 	# Attempt to unmount in case there are some leftovers after
@@ -74,8 +75,8 @@ kbfsd_prestart()
 	if ! mkdir -p -- "${kbfsd_mountpoint}"; then
 		err 1 "Cannot create the '${kbfsd_mountpoint}' directory.'"
 	fi
-	if ! chown "${kbfsd_username}" "${kbfsd_mountpoint}"; then
-		err 1 "Cannot set ${kbfsd_username} as the owner of ${kbfsd_mountpoint}."
+	if ! chown "${kbfsd_user}" "${kbfsd_mountpoint}"; then
+		err 1 "Cannot set ${kbfsd_user} as the owner of ${kbfsd_mountpoint}."
 	fi
 
 	# Make it possible to mount filesystems as a normal user.
@@ -85,28 +86,32 @@ kbfsd_prestart()
 
 	# Add the specified user account to the opearator group so that it
 	# could use the /dev/fuse device.
-	if ! pw groupmod operator -m "${kbfsd_username}"
-	then
-		err 1 "Cannot add ${kbfsd_username} to the operator group."
+	if ! pw groupmod operator -m "${kbfsd_user}"; then
+		err 1 "Cannot add ${kbfsd_user} to the operator group."
 	fi
 
 	# The Keybase client has to be initiated so that
-	# "/home/${kbfsd_username}/.config/keybase/keybased.sock" and
-	# "/home/${kbfsd_username}/.config/keybase/kbfsd.sock" are present.
-	su "${kbfsd_username}" -c "%%LOCALBASE%%/keybase login ${kbfsd_keybase_username}"
-	su "${kbfsd_username}" -c "%%LOCALBASE%%/keybase fs ls ${kbfsd_mountpoint} > /dev/null 2>&1"
+	# "/home/${kbfsd_user}/.config/keybase/keybased.sock" and
+	# "/home/${kbfsd_user}/.config/keybase/kbfsd.sock" are present.
+	su -l "${kbfsd_user}" -c "%%LOCALBASE%%/bin/keybase login ${kbfsd_keybase_username}" > /dev/null 2>&1
+	su -l "${kbfsd_user}" -c "%%LOCALBASE%%/bin/keybase fs ls ${kbfsd_mountpoint} > /dev/null 2>&1"
+	for _f in \
+	    "/home/${kbfsd_user}/.config/keybase/kbfsd.sock" \
+	    "/home/${kbfsd_user}/.config/keybase/keybased.sock"
+	do
+		if [ ! -S "${_f}" ]; then
+			err 1 "Missing the \"${_f}\" file."
+		fi
+	done
 
 	return 0
 }
 
-kbfsd_start()
+kbfsd_poststop()
 {
-	check_pidfile "${pidfile}" "${procname}"
-	# It has to be done manually because the su(1) mechanism present
-	# in rc.subr(8) uses the "-m" flag, which causes kbfsfuse to look
-	# for files in root's directories instead of the directories of
-	# ${kbfsd_username}.
-	daemon -p "${pidfile}" su "${kbfsd_username}" -c "${command} ${command_args}"
+	# Attempt to unmount in case there are some leftovers terminating
+	# kbfsfuse too rapidly.
+	umount "${kbfsd_mountpoint}" > /dev/null 2>&1
 }
 
 run_rc_command "$1"
